#!/bin/bash

echo "remote post-receive disabled, refresh manually"

#repository=$(basename ${PWD})
#course=${repository%.*}

#exec wget "http://localhost:3000/courses/${course}/refresh" \
#	-nv --max-redirect 0 -O /dev/null

