inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'ext/**/*'
    - 'db/**/*'

# Style
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
