#!/bin/bash
#
# - Picks between sudo, rbenv sudo and rvmsudo
# - Makes rbenv sudo PATH-preserving, if picked
# - Does a bundle exec
#

if [ -n "`which rbenv`" ]; then
  echo "Using rbenv sudo"
  rbenv sudo env PATH="$PATH" bundle exec $@
elif [ -n "`which rvmsudo`" ]; then
  echo "Using rvmsudo"
  rvmsudo bundle exec $@
else
  echo "Using sudo"
  sudo bundle exec $@
fi

