# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1ebd40839c8371fb7f086dded25bdb6ff3f6ca158adfd74df5cab808a5b45e7d900a1406ee9e042b254a62151d6debdf87d5785b31ac85c3f262e9866433009
  openid_connect_signing_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCjlWtlLaB4L/9U
    2N0ld800cna9yCt8CFBjKMN/zEMZ5NX+WwjxghJB4oIz75AiBeZGlywdA0Xjo0hi
    O5lI9xHwkuamx5Tn+KQp78uPXymshifXhrtDdXVdqesuUxspfBVHnorCl06M4YU4
    LPTqh25NrI9t7PhB0AyT7J5rqIrAcov9lqsH6yTfSI2Ghb+wLYlsmgNmF+5yerv4
    PqxIIZ1V0yKRBHn7M/BUFWC/oL84YZjMcAEgVAVFbXdgKY930v+Vxas+bf+/uCan
    vsiKe5pnXMeEkKoZYIznlEhspArV2GkCQcY0FXkmkAcUpj15xiH0GFeak087QVC+
    ty+C1J2zAgMBAAECggEACsXgWL10f/XJPvE5PypwnS+cmksAch6qDJ22okf1c1Ma
    tLGSGTWTtjsQkBMKzvLMg4GZKh/5DlDGh5GdOqzqxYknH3ytVcmOJiTgpwSBXhdH
    sG3zDzJBFHYIQvi+JTFCxYCvarlENwrzFwv+5SMeJIdkuryMbOkiqus+U6C54oqN
    rxhbR83LM3ujIq1Q3BIsn3mDnVKxLrhbkfKoZsEgQyu5OOqqIYV7dsYdCv7SHfXx
    Qv2zBrbvIOwhflzymmYttMfP7pfs/F8frBizB5oSLaEO66BlyPKcDeCFGNbdnDvm
    62zHczertWeuNjuhylCPWOk0VlLs/ZDAj9GHQcZLgQKBgQDHad7aPIRzD4xqa6YJ
    5OiTtlCmC8IxqyJUNAIgIYjotNKI7WUsbPxza8mMDJrpnXfY4Lb43AYzXBzkq+74
    ukrxRQvWWTWkhSGWNIvjP77HlpipeXLgXkPLvDb+XpBFneI4CSlcQroq5S7KwI5Y
    HkT9BdwFhl6D2jeAkzLNmkIuEQKBgQDSALwuvRoeovZY0zIQ0X7PLby5tvcpHwn5
    iuztV544hqrtWlEQkcxtO7eOZ9IL4/wQiF+0QN25uD8cKjznckZUXijTVEPFBxjQ
    yvY1tEBlOH4YEkZGcrnCU6n76rpqo9Lj545lrCE90iSFSkGm1+zCnnwRkrUw5VL/
    0yI2iCdbgwKBgQCiRHtMWOxqeJ+JRZmx+WxsLnIH/A+EvT5NCJkmLkOrIOEk/RBU
    C0eOYIp8BRHVwgZxG8KoVNpS1sTIK0Rlb6pmFApi3OryukavZIjkXc3PubL2TVZ2
    Tx6Z3cleSfLaQ3R+pq3aXo4BM8dUw0XRXKhEwIzejg3A+0Qowx8XAUyTEQKBgGyD
    BLoB7KU3/6MWPiCCn8veDk7IRB5zc2wGZTaet5rtuxS6PnkZXVB0MvzamKacP3sr
    fIhfnDKDCdk72gyd98lQfjf0qq/8Ys5AkcheQ4gKEN3PU5DDZ0kKgiMxvvGrhSVO
    WT4gG20eUNCu9g2INUa7LdDGxelmFeUq69rRr8SRAoGBAIQnI6mUaUTEfZV+CcK6
    76ezVm/l6LCaGZrOXHkT78+1eYLMoEPZrJ7pRX+Fa05L6PWwkusqQIWwvpzfsLB3
    Vt2Wz6vpQJBoEWdIAm57h/BmXYgRSoZl8ilaQpGDwvqQDQ0TcED95vtEvXsib4RV
    wvTexLwtU6i38xTpGMeTsQVx
    -----END PRIVATE KEY-----
  tmc_server_secret_for_communicating_to_secret_project: <%= ENV["TMC_SERVER_SECRET_FOR_COMMUNICATING_TO_SECRET_PROJECT"] || "Zm9yIGxvY2FsIGRldmVsb3BtZW50IG9ubHksIGludGVudGlvbmFsbHkgcHVibGlj" %>

test:
  secret_key_base: fdc6fb714d1447ce6ab48e3f216e5419b567dcfbc9a713273f8f193c3f13807105136de778516770d451485a8fc31e8d58eae6259e94e2a4b53f547329bb1486
  openid_connect_signing_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCjlWtlLaB4L/9U
    2N0ld800cna9yCt8CFBjKMN/zEMZ5NX+WwjxghJB4oIz75AiBeZGlywdA0Xjo0hi
    O5lI9xHwkuamx5Tn+KQp78uPXymshifXhrtDdXVdqesuUxspfBVHnorCl06M4YU4
    LPTqh25NrI9t7PhB0AyT7J5rqIrAcov9lqsH6yTfSI2Ghb+wLYlsmgNmF+5yerv4
    PqxIIZ1V0yKRBHn7M/BUFWC/oL84YZjMcAEgVAVFbXdgKY930v+Vxas+bf+/uCan
    vsiKe5pnXMeEkKoZYIznlEhspArV2GkCQcY0FXkmkAcUpj15xiH0GFeak087QVC+
    ty+C1J2zAgMBAAECggEACsXgWL10f/XJPvE5PypwnS+cmksAch6qDJ22okf1c1Ma
    tLGSGTWTtjsQkBMKzvLMg4GZKh/5DlDGh5GdOqzqxYknH3ytVcmOJiTgpwSBXhdH
    sG3zDzJBFHYIQvi+JTFCxYCvarlENwrzFwv+5SMeJIdkuryMbOkiqus+U6C54oqN
    rxhbR83LM3ujIq1Q3BIsn3mDnVKxLrhbkfKoZsEgQyu5OOqqIYV7dsYdCv7SHfXx
    Qv2zBrbvIOwhflzymmYttMfP7pfs/F8frBizB5oSLaEO66BlyPKcDeCFGNbdnDvm
    62zHczertWeuNjuhylCPWOk0VlLs/ZDAj9GHQcZLgQKBgQDHad7aPIRzD4xqa6YJ
    5OiTtlCmC8IxqyJUNAIgIYjotNKI7WUsbPxza8mMDJrpnXfY4Lb43AYzXBzkq+74
    ukrxRQvWWTWkhSGWNIvjP77HlpipeXLgXkPLvDb+XpBFneI4CSlcQroq5S7KwI5Y
    HkT9BdwFhl6D2jeAkzLNmkIuEQKBgQDSALwuvRoeovZY0zIQ0X7PLby5tvcpHwn5
    iuztV544hqrtWlEQkcxtO7eOZ9IL4/wQiF+0QN25uD8cKjznckZUXijTVEPFBxjQ
    yvY1tEBlOH4YEkZGcrnCU6n76rpqo9Lj545lrCE90iSFSkGm1+zCnnwRkrUw5VL/
    0yI2iCdbgwKBgQCiRHtMWOxqeJ+JRZmx+WxsLnIH/A+EvT5NCJkmLkOrIOEk/RBU
    C0eOYIp8BRHVwgZxG8KoVNpS1sTIK0Rlb6pmFApi3OryukavZIjkXc3PubL2TVZ2
    Tx6Z3cleSfLaQ3R+pq3aXo4BM8dUw0XRXKhEwIzejg3A+0Qowx8XAUyTEQKBgGyD
    BLoB7KU3/6MWPiCCn8veDk7IRB5zc2wGZTaet5rtuxS6PnkZXVB0MvzamKacP3sr
    fIhfnDKDCdk72gyd98lQfjf0qq/8Ys5AkcheQ4gKEN3PU5DDZ0kKgiMxvvGrhSVO
    WT4gG20eUNCu9g2INUa7LdDGxelmFeUq69rRr8SRAoGBAIQnI6mUaUTEfZV+CcK6
    76ezVm/l6LCaGZrOXHkT78+1eYLMoEPZrJ7pRX+Fa05L6PWwkusqQIWwvpzfsLB3
    Vt2Wz6vpQJBoEWdIAm57h/BmXYgRSoZl8ilaQpGDwvqQDQ0TcED95vtEvXsib4RV
    wvTexLwtU6i38xTpGMeTsQVx
    -----END PRIVATE KEY-----
  tmc_server_secret_for_communicating_to_secret_project: <%= ENV["TMC_SERVER_SECRET_FOR_COMMUNICATING_TO_SECRET_PROJECT"] || "Zm9yIGxvY2FsIGRldmVsb3BtZW50IG9ubHksIGludGVudGlvbmFsbHkgcHVibGlj" %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  openid_connect_signing_key: <%=  (ENV["OPENID_CONNECT_SIGNING_KEY"] || "").dump %>
  tmc_server_secret_for_communicating_to_secret_project: <%= ENV["TMC_SERVER_SECRET_FOR_COMMUNICATING_TO_SECRET_PROJECT"] %>
